# Copyright (c) 2021 Vũ Quang Trọng <vuquangtrong@gmail.com>

site_name: Code Inside Out
site_url: https://www.codeinsideout.com/ # must have the trailing slash
site_author: vqtrong
site_email: vuquangtrong@gmail.com
site_description: >-
    Interesting stuff in Embedded Systems and IoT Applications.
    From hardwares to cloud applications. Step by step.
site_description_full: >-
    Interesting stuff in Embedded Systems and IoT Applications.<br/>
    From hardwares to cloud applications. Step by step.<br/>
    (ﾉ◕ヮ◕)ﾉ*:・ﾟ✧
site_keywords: embedded systems application programming

# copyright: © 2021 Code Inside Out

# a hacky workaround as I don't want to replace the template partials\footer.html, 
# below html code works together with extracopyright in overrides\main.html
copyright: >-
    © 2021 Code Inside Out <div style="display:none"><div>

theme:
    name: material
    custom_dir: overrides
    palette:
        primary: white
    font:
        text: Noto Serif
        code: Roboto Mono
    icon:
        logo: fontawesome/solid/code
    favicon: favicon.ico
    features:
        - navigation.tabs
        - navigation.top
        - header.autohide

extra_css:
    - assets/extra.css

extra_javascript:
    - assets/extra.js


markdown_extensions:
    # official
    - meta
    - admonition
    - attr_list
    - def_list
    - sane_lists
    - tables
    - md_in_html
    - footnotes
    - toc:
        permalink: ⚓︎
        slugify: !!python/name:pymdownx.slugs.uslugify
        toc_depth: 4

    # pymdownx
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:mermaid2.fence_mermaid
    - pymdownx.highlight:
        linenums_style: pymdownx-inline
    - pymdownx.inlinehilite
    - pymdownx.tabbed
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.critic
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg

    # undocumented
    - pymdownx.snippets
    - pymdownx.saneheaders
    - pymdownx.smartsymbols

    # 3rd party
    - markdown_captions
    - cell_row_span
    - customblocks
    - kbdextension:
        brackets_css: button # [[button]]
        enable_parens: true
        parens_css: menu # ((menu))
        enable_braces: false # conflict with mkdocs-macros-plugin
        braces_css: action # {{action}}


plugins:
    - search
    - git-revision-date:
        as_datetime: true
    - git-revision-date-localized:
        enable_creation_date: true
    - macros
    - mermaid2
    - awesome-pages:
        collapse_single_pages: true        
    - pdf-with-js:
        enable: false
        filename_use_full_title: false
        display_header_footer: true
        header_template: >-
            <div style="font-size:8px; margin:auto; color:lightgray;">
                <span class=title></span>
            </div>
        footer_template: >-
            <div style="font-size:8px; margin:auto; color:lightgray;">
                Page <span class="pageNumber"></span> of <span class="totalPages"></span>
            </div>

# google_analytics:
    # - UA-42618265-2
    # - auto


extra:
    # disqus: 'vuquangtrong-github-io'
    social:
        - icon: fontawesome/brands/github-alt
          link: https://github.com/vuquangtrong
        - icon: fontawesome/brands/facebook-f
          link: https://facebook.com/trongvq
        - icon: fontawesome/brands/linkedin-in
          link: https://www.linkedin.com/in/vqtrong
