# Copyright (c) 2020 Vũ Quang Trọng <vuquangtrong@gmail.com>

site_name: Blogging with Material for Mkdocs
site_url: http://localhost:8000/ # must have the trailing slash
site_author: vuquangtrong@gmail.com
site_description: >-
  Write your blog in technical documentation style!

copyright: >- # can use HTML text, but should be on one line
  © 2020 <a href="https://www.codeinsideout.com/">Code Inside Out</a>

theme:
  name: material
  custom_dir: overrides
  font:
    text: Noto Serif
    code: Roboto Mono
    # content:
      # text: Noto Serif
      # code: Roboto Mono
  features:
    - navigation.tabs
  logo: assets/logo.png
  favicon: assets/favicon.ico

extra_css:
  - stylesheets/root.css

plugins:
  - search:
  - exclude:
      glob:
        - "draft/*"
  - markdown-filter:
  - macros: # before change the default block marks {{}}, 
            # please check other plugin which relies on jinja in markdown
      j2_block_start_string: '{[%'
      j2_block_end_string: '%]}'
      j2_variable_start_string: '{['
      j2_variable_end_string: ']}'
  - awesome-pages:
      collapse_single_pages: true
  - redirects:
      redirect_maps:
  - minify:
      minify_html: true
      htmlmin_opts:
        remove_comments: true

markdown_extensions:
  - kbdextension:
      brackets_css: button # [[button]]
      enable_parens: true
      parens_css: menu # ((menu))
      enable_braces: true
      braces_css: action # {{action}} or
                         # {{ "{{action}}" }} when use mkdocs-macros-plugin with default {{}}
  - markdown_captions:
  - custom-span-class:
  - customblocks:
  - abbr:
  - attr_list:
  - def_list:
  # - fenced_code: # replaced by pymdownx.superfences
  - footnotes:
  - md_in_html:
  - tables:
  - cell_row_span:
  - admonition:
  # - sane_lists: # cause some weird renders when use with pymdownx
  # - nl2br: # cause some weird render when use with pymdownx, 
             # can use \n with pymdownx.escapeall extension
  - meta:
  - toc:
      permalink: ⚓︎
      slugify: !!python/name:pymdownx.slugs.uslugify
      toc_depth: 4 # from h2 to h4 only
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.details:
  - pymdownx.superfences:
  - pymdownx.highlight:
      # linenums: true
  - pymdownx.inlinehilite:
  # - pymdownx.keys: # ++key++ syntax is hard to read in markdown, use kbdextension instead
  - pymdownx.tabbed:
  - pymdownx.caret:
  - pymdownx.mark:
  - pymdownx.tilde:
  - pymdownx.critic:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.progressbar:
  - pymdownx.saneheaders:
  - pymdownx.escapeall:
      hardbreak: true
      nbsp: true
  - pymdownx.magiclink:
  # - pymdownx.smartsymbols:

# google_analytics:
  # - UA-XXXXXXXX-X
  # - auto

extra:
  # disqus: 'your-id'
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/vuquangtrong
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/trongvq
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/vqtrong

nav:
  - index.md
  - Projects:
    - projects.md
  - ...
  - About: 
    - about.md
  - Tags: 
    - tags.md